[common]
start_task_file = "@example_task_file@"
archive_num = 10
ratio = 3

[compute]
threads = 20
archive_prefix = "@CMAKE_CURRENT_BINARY_DIR@/archive/"
archive_suffix = ""
archive_extension = "nfar.zst"

[render]
threads = 20
render_once = false
image_per_frame = 60
extra_image_num = 4
image_prefix = "@CMAKE_CURRENT_BINARY_DIR@/image/"
image_suffix = ""
render_json_file = "@example_render_json_file@"

[video]
threads = 4
prefer_symlink = true
#ffmpeg_exe = "ffmpeg"
product_name = "product"

[video.temp]
video_prefix = "@CMAKE_CURRENT_BINARY_DIR@/video/temp/"
video_suffix = ""
encoder_flags = "-crf 30"
encoder = "libx264"
extension = "mp4"

[video.product]
video_prefix = "@CMAKE_CURRENT_BINARY_DIR@/video/"
video_suffix = ""
encoder_flags = "-crf 18 -pix_fmt yuv420p"
encoder = "libx265"
extension = "mp4"