[common]
start_task_file = "@example_task_file@"
archive_num = 10
ratio = 3

[compute]
threads = 20
archive_prefix = "@CMAKE_CURRENT_BINARY_DIR@/archive/"
archive_suffix = ""
archive_extension = "nfar.zst"

[render]
threads = 20
render_once = false
image_per_frame = 60
extra_image_num = 4
image_prefix = "@CMAKE_CURRENT_BINARY_DIR@/image/"
image_suffix = ""
render_json_file = "@example_render_json_file@"

[video]
threads = 4
prefer_symlink = true
#ffmpeg_exe = "ffmpeg"
product_name = "product"

temp.video_prefix = "@CMAKE_CURRENT_BINARY_DIR@/video/temp/"
temp.video_suffix = ""
temp.encoder_flags = "-crf 30"
temp.encoder = "libx264"
temp.extension = "mp4"
product.video_prefix = "@CMAKE_CURRENT_BINARY_DIR@/video/"
product.video_suffix = ""
product.encoder_flags = "-crf 18"
product.encoder = "libx264"
product.extension = "mp4"