set(CPACK_PACKAGE_NAME "NewtonFractalZoom")
if (NOT (${CMAKE_BUILD_TYPE} STREQUAL "Release"))
    set(CPACK_PACKAGE_NAME "${CPACK_PACKAGE_NAME}-${CMAKE_BUILD_TYPE}")
endif ()

set(CPACK_PACKAGE_VENDOR "TokiNoBug")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_RPM_PACKAGE_LICENSE "GPLv3.0")

include(CPack)